name: Deploy to server

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./target/app.jar"
          target: "/var/sphinxes/"

      - name: Run application as service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/sphinxes
            cp /var/sphinxes/target/app.jar /var/sphinxes/app.jar
            rm -rf /var/sphinxes/target
            sudo systemctl stop sphinxes.service
            sudo systemctl start sphinxes.service